{% set name = "k-diagram" %}
{% set version = "1.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: 99065c307e9302fe7115956e2a5ea5fe7ee8746361a4c66f55e80ad239f14a37

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - k-diagram = kdiagram.cli:main
    - kdiagram = kdiagram.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=69
    - wheel
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - pandas >=1.0
    - scipy >=1.5
    - matplotlib-base >=3.3
    - seaborn >=0.11
    - scikit-learn >=0.24
    - typing-extensions

test:
  imports:
    - kdiagram
    - kdiagram.cli
  commands:
    - k-diagram --help
    - kdiagram --help
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: "https://github.com/earthai-tech/k-diagram"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "Rethinking Forecasting Uncertainty via Polar-Based Visualization"
  doc_url: "https://k-diagram.readthedocs.io/"
  dev_url: "https://github.com/earthai-tech/k-diagram"

extra:
  recipe-maintainers:
    - earthai-tech
